name: Cargo Check

on:
  push:
   branches:
     - main

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
    - name: Cargo Check
      run: cargo check